import { fortunesDatabase } from './fortunesData.js';
import { generatePersonalizedAIFortune, fetchRemoteAIPrediction, zodiacElements } from './aiEngine.js';

export { zodiacElements, fetchRemoteAIPrediction };

export const zodiacSigns = [
  { id: 'aries', icon: '♈', name: { en: 'Aries', tr: 'Koç', de: 'Widder', fr: 'Bélier', it: 'Ariete', el: 'Kριός', es: 'Aries', zh: '白羊座', ja: '牡羊座', ko: '양자리' } },
  { id: 'taurus', icon: '♉', name: { en: 'Taurus', tr: 'Boğa', de: 'Stier', fr: 'Taureau', it: 'Toro', el: 'Ταύρος', es: 'Tauro', zh: '金牛座', ja: '牡牛座', ko: '황소자리' } },
  { id: 'gemini', icon: '♊', name: { en: 'Gemini', tr: 'İkizler', de: 'Zwillinge', fr: 'Gémeaux', it: 'Gemelli', el: 'Δίδυμοι', es: 'Géminis', zh: '双子座', ja: '双子座', ko: '쌍둥이자리' } },
  { id: 'cancer', icon: '♋', name: { en: 'Cancer', tr: 'Yengeç', de: 'Krebs', fr: 'Cancer', it: 'Cancro', el: 'Kαρκίνος', es: 'Cáncer', zh: '巨蟹座', ja: '蟹座', ko: '게자리' } },
  { id: 'leo', icon: '♌', name: { en: 'Leo', tr: 'Aslan', de: 'Löwe', fr: 'Lion', it: 'Leone', el: 'Λέων', es: 'Leo', zh: '狮子座', ja: '狮子座', ko: '사자자리' } },
  { id: 'virgo', icon: '♍', name: { en: 'Virgo', tr: 'Başak', de: 'Jungfrau', fr: 'Vierge', it: 'Vergine', el: 'Παρθένος', es: 'Virgo', zh: '处女座', ja: '乙女座', ko: '처녀자리' } },
  { id: 'libra', icon: '♎', name: { en: 'Libra', tr: 'Terazi', de: 'Waage', fr: 'Balance', it: 'Bilancia', el: 'Ζυγός', es: 'Libra', zh: '天秤座', ja: '天秤座', ko: '천칭자리' } },
  { id: 'scorpio', icon: '♏', name: { en: 'Scorpio', tr: 'Akrep', de: 'Skorpion', fr: 'Scorpion', it: 'Scorpione', el: 'Σκορπιός', es: 'Escorpio', zh: '天蝎座', ja: '蠍座', ko: '전갈자리' } },
  { id: 'sagittarius', icon: '♐', name: { en: 'Sagittarius', tr: 'Yay', de: 'Schütze', fr: 'Sagittaire', it: 'Sagittario', el: 'Τοξότης', es: 'Sagitario', zh: '射手座', ja: '射手座', ko: '사수자리' } },
  { id: 'capricorn', icon: '♑', name: { en: 'Capricorn', tr: 'Oğlak', de: 'Steinbock', fr: 'Capricorne', it: 'Capricorno', el: 'Αιγόκερως', es: 'Capricornio', zh: '摩羯座', ja: '山羊座', ko: '염소자리' } },
  { id: 'aquarius', icon: '♒', name: { en: 'Aquarius', tr: 'Kova', de: 'Wassermann', fr: 'Verseau', it: 'Acquario', el: 'Υδροχόος', es: 'Acuario', zh: '水瓶座', ja: '水瓶座', ko: '물병자리' } },
  { id: 'pisces', icon: '♓', name: { en: 'Pisces', tr: 'Balık', de: 'Fische', fr: 'Poissons', it: 'Pesci', el: 'Ιχθύες', es: 'Piscis', zh: '双鱼座', ja: '魚座', ko: '물고기자리' } }
];

export const categories = [
  { id: 'general', name: { en: '🌟 General Wisdom', tr: '🌟 Genel Hikmet', de: '🌟 Allgemeine Weisheit', fr: '🌟 Sagesse Générale', it: '🌟 Saggezza Generale', el: '🌟 Γενική Σοφία', es: '🌟 Sabiduría General', zh: '🌟 综合智慧', ja: '🌟 総合運', ko: '🌟 종합운' } },
  { id: 'love', name: { en: '💖 Love & Soul', tr: '💖 Aşk & Gönül', de: '💖 Liebe & Seele', fr: '💖 Amour & Âme', it: '💖 Amore & Anima', el: '💖 Αγάπη & Ψυχή', es: '💖 Amor & Alma', zh: '💖 缘分与爱', ja: '💖 恋愛・縁', ko: '💖 연애와 사랑' } },
  { id: 'career', name: { en: '💼 Mastery & Wealth', tr: '💼 Başarı & Bereket', de: '💼 Meisterschaft', fr: '💼 Succès & Prospérité', it: '💼 Carriera & Successo', el: '💼 Επιτυχία', es: '💼 Éxito & Abundancia', zh: '💼 功名与财富', ja: '💼 仕事・金運', ko: '💼 성공과 재물' } },
  { id: 'health', name: { en: '🌿 Inner Peace', tr: '🌿 Huzur & Şifa', de: '🌿 Innere Ruhe', fr: '🌿 Paix Intérieure', it: '🌿 Pace Interiore', el: '🌿 Εσωτερική Γαλήνη', es: '🌿 Paz Interior', zh: '🌿 身心安康', ja: '🌿 健康・癒やし', ko: '🌿 건강과 평화' } }
];

export const fortunes = fortunesDatabase;

export function getFortunesDatabase() {
  const custom = localStorage.getItem('fc_custom_fortunes_db');
  if (custom) {
    try {
      return JSON.parse(custom);
    } catch (e) {}
  }
  return fortunesDatabase;
}

export function saveFortunesDatabase(db) {
  localStorage.setItem('fc_custom_fortunes_db', JSON.stringify(db));
}

export function getRandomFortune(lang = 'tr', category = 'general', userProfile = {}) {
  const db = getFortunesDatabase();
  const langFortunes = db[lang] || db.tr || db.en;
  let categoryList = langFortunes[category] || langFortunes.general || Object.values(langFortunes)[0];

  if (Array.isArray(categoryList) && categoryList.length > 0) {
    const randomIndex = Math.floor(Math.random() * categoryList.length);
    const baseFortune = categoryList[randomIndex];
    return generatePersonalizedAIFortune(userProfile, lang, baseFortune);
  }

  return "Sabırla dikilen tohum, hiç beklemediğin anda en tatlı meyvesini verir.";
}

export const uiText = {
  tr: {
    appTitle: "Şans Kurabiyesi AI",
    paperText: "✨ ŞANS KURABİYESİ",
    subtitle: "Şans kurabiyesini kırmak için dokunun!",
    pillText: "Sihir içeride seni bekliyor",
    cardTitle: "Senin Şans Kurabiyen",
    luckyTitle: "Günün Şanslı Sayıları",
    btnAgain: "Yeniden Başla",
    btnStory: "Hikaye Kartı",
    btnShareStory: "Hikayeyi Paylaş",
    shareUnavailable: "Paylaşım bu cihazda kullanılamıyor.",
    toastShared: "Paylaşıldı! 🌟",
    profileTitle: "Kişisel Profilim",
    historyTitle: "Geçmiş Şans Kurabiyelerim",
    selectZodiac: "Burcunuz",
    selectCategory: "Odak Alanınız",
    namePlaceholder: "Adınızı girin...",
    btnSaveProfile: "Profili Kaydet",
    btnClearHistory: "Temizle",
    noHistory: "Henüz geçmiş Şans Kurabiyen bulunmuyor.",
    aiCrafting: "Şans kurabiyesi kırılıyor...",
    modalTitle: "Hikaye Kartı",
    btnClose: "Kapat",
    socialLoginLabel: "Verilerini kaydetmek için bağlan",
    btnGoogle: "Google ile Giriş",
    btnApple: "Apple ile Giriş",
    btnSoon: "Yakında",
    dividerOr: "veya misafir olarak devam et",
    labelLang: "Uygulama Dili:",
    labelName: "İsim:",
    labelBirthdate: "Doğum Tarihi:",
    labelBirthtime: "Doğum Saati:",
    labelRising: "✨ Yükselen Burç:",
    labelSun: "☀️ Güneş Burcu:",
    adVideoTitle: "🎬 Sponsorlu Ödüllü Video",
    adVideoDesc: "Premium AI Şans Kurabiyesi hazırlanıyor...",
    adTimerPrefix: "Kapanıyor:",
    btnClaimReward: "🎁 Ödülü Al",
    risingPrefix: "🌅 Yükselen: ",
    premiumTopLabel: "Premium",
    premiumStoreTitle: "VIP Premium Paketi",
    premiumStoreSubtitle: "Günlük 5 Premium AI Şans Kurabiyesi & Reklamsız Deneyim",
    planBadge: "🔥 En Çok Tercih Edilen",
    planYearlyTitle: "Aylık VIP Abonelik",
    planYearlyPeriod: "/ay",
    planYearlyNote: "günlük yalnızca 3.3 TL",
    planMonthlyTitle: "Aylık Plan",
    planMonthlyPeriod: "/ay",
    featUnlimited: "Günlük 5 Premium AI Şans Kurabiyesi",
    featRising: "Yükselen Burç Analizi",
    featNoAds: "Tamamen Reklamsız Kullanım",
    featHistory: "Sınırsız Şans Kurabiyesi Geçmişi",
    btnBuyYearly: "Aboneliği Başlat (99 TL/ay)",
    btnBuyMonthly: "Aylık Başla",
    btnRestorePurchases: "Satın Alımları Geri Yükle",
    premiumLegalText: "Abonelik her ay otomatik yenilenir. Mağaza ayarlarınızdan dilediğiniz zaman iptal edebilirsiniz.",
    btnWatchAdTitle: "Premium AI Şans Kurabiyesi Kazan",
    btnPremiumTitle: "Premium Paket",
    btnPremiumSub: "Sınırsız & Reklamsız"
  },
  en: {
    appTitle: "Fortune Cookie AI",
    paperText: "✨ FORTUNE COOKIE",
    subtitle: "Tap the cookie to crack it open!",
    pillText: "Magic awaits inside",
    cardTitle: "Your Fortune Cookie",
    luckyTitle: "Your Lucky Numbers",
    btnAgain: "Try Again",
    btnStory: "Story Card",
    btnShareStory: "Share Story",
    shareUnavailable: "Sharing is not available on this device.",
    toastShared: "Shared! 🌟",
    profileTitle: "My Profile & Settings",
    historyTitle: "Fortune Cookie History",
    selectZodiac: "Zodiac Sign",
    selectCategory: "Focus Category:",
    namePlaceholder: "Enter your name...",
    btnSaveProfile: "Save Profile",
    btnClearHistory: "Clear",
    noHistory: "No Fortune Cookie history saved yet.",
    aiCrafting: "Cracking your cookie...",
    modalTitle: "Story Card Generator",
    btnClose: "Close",
    socialLoginLabel: "Connect to save your data",
    btnGoogle: "Sign in with Google",
    btnApple: "Sign in with Apple",
    btnSoon: "Soon",
    dividerOr: "or continue as guest",
    labelLang: "App Language:",
    labelName: "Name:",
    labelBirthdate: "Birth Date:",
    labelBirthtime: "Birth Time:",
    labelRising: "✨ Rising Sign:",
    labelSun: "☀️ Sun Sign:",
    adVideoTitle: "🎬 Sponsored Reward Video",
    adVideoDesc: "Unlocking 24-Hour Premium AI Horoscopes & Rising Sign Guidance...",
    adTimerPrefix: "Closing in",
    btnClaimReward: "🎁 Claim Premium Reward",
    risingPrefix: "🌅 Rising: ",
    premiumTopLabel: "Premium",
    premiumStoreTitle: "VIP Premium Pass",
    premiumStoreSubtitle: "5 Premium AI Fortune Cookies Daily & Ad-Free Experience",
    planBadge: "🔥 Best Value",
    planYearlyTitle: "Monthly VIP Plan",
    planYearlyPeriod: "/mo",
    planYearlyNote: "only $2.99 / month",
    planMonthlyTitle: "Monthly Plan",
    planMonthlyPeriod: "/mo",
    featUnlimited: "5 Premium AI Fortune Cookies Daily",
    featRising: "Rising Sign Analysis",
    featNoAds: "100% Ad-Free Experience",
    featHistory: "Full Fortune History",
    btnBuyYearly: "Start VIP Pass ($2.99/mo)",
    btnBuyMonthly: "Start Monthly",
    btnRestorePurchases: "Restore Purchases",
    premiumLegalText: "Subscription auto-renews monthly. Cancel anytime in Store Settings.",
    btnWatchAdTitle: "Get Free AI Fortune",
    btnPremiumTitle: "Go Premium",
    btnPremiumSub: "Unlimited & Ad-Free"
  },
  de: {
    appTitle: "Glückskeks AI",
    subtitle: "Tippe auf den Keks, um ihn zu öffnen!",
    pillText: "Magie wartet im Inneren",
    cardTitle: "Dein Glücksspruch",
    luckyTitle: "Deine Glückszahlen",
    btnAgain: "Neuen Keks Öffnen",
    btnStory: "Story Karte",
    btnShareStory: "Story Teilen",
    shareUnavailable: "Teilen ist auf diesem Gerät nicht verfügbar.",
    toastShared: "Geteilt! 🌟",
    profileTitle: "Mein Profil & Einstellungen",
    historyTitle: "Verlauf",
    selectZodiac: "Sternzeichen",
    selectCategory: "Fokusbereich:",
    namePlaceholder: "Dein Name...",
    btnSaveProfile: "Profil Speichern",
    btnClearHistory: "Löschen",
    noHistory: "Noch kein Verlauf vorhanden.",
    aiCrafting: "Keks wird geöffnet...",
    modalTitle: "Story Karte",
    btnClose: "Schließen",
    socialLoginLabel: "Verbinden um Daten zu speichern",
    btnGoogle: "Mit Google anmelden",
    btnApple: "Mit Apple anmelden",
    btnSoon: "Demnächst",
    dividerOr: "oder als Gast fortfahren",
    labelLang: "App-Sprache:",
    labelName: "Name:",
    labelBirthdate: "Geburtsdatum:",
    labelBirthtime: "Geburtszeit:",
    labelRising: "✨ Aszendent:",
    labelSun: "☀️ Sternzeichen:",
    adVideoTitle: "🎬 Gesponsortes Video",
    adVideoDesc: "24-Stunden-KI-Orakel wird freigeschaltet...",
    adTimerPrefix: "Schließt in",
    btnClaimReward: "🎁 Belohnung Holen",
    risingPrefix: "🌅 Aszendent: ",
    premiumTopLabel: "Premium",
    premiumStoreTitle: "Premium-Pass",
    premiumStoreSubtitle: "Unbegrenzte KI-Orakel & Astrologie-Reise",
    planBadge: "🔥 Beliebtest",
    planYearlyTitle: "Jahres-Abo",
    planYearlyPeriod: "/Jahr",
    planYearlyNote: "nur $1.25 / Monat",
    planMonthlyTitle: "Monats-Abo",
    planMonthlyPeriod: "/Monat",
    featUnlimited: "Unbegrenzte KI-Orakel",
    featRising: "Aszendenten-Analyse",
    featNoAds: "Werbefreies Erlebnis",
    featHistory: "Vollständiger Verlauf",
    btnBuyYearly: "Jetzt Starten",
    btnBuyMonthly: "Monatlich Starten",
    premiumLegalText: "Automatische Verlängerung. Jederzeit kündbar.",
    btnWatchAdTitle: "Gratis KI-Orakel",
    btnPremiumTitle: "Premium Werden",
    btnPremiumSub: "Unbegrenzt & Werbefrei"
  },
  fr: {
    appTitle: "Biscuit de Fortune AI",
    subtitle: "Appuyez sur le biscuit pour l'ouvrir!",
    pillText: "La magie vous attend à l'intérieur",
    cardTitle: "Votre Prédiction",
    luckyTitle: "Vos Numéros Chanceux",
    btnAgain: "Autre Prédiction",
    btnStory: "Carte Story",
    btnShareStory: "Partager Story",
    shareUnavailable: "Le partage n’est pas disponible sur cet appareil.",
    toastShared: "Partagé! 🌟",
    profileTitle: "Mon Profil & Paramètres",
    historyTitle: "Historique",
    selectZodiac: "Signe Astrologique",
    selectCategory: "Catégorie:",
    namePlaceholder: "Votre prénom...",
    btnSaveProfile: "Enregistrer Profil",
    btnClearHistory: "Effacer",
    noHistory: "Aucun historique disponible.",
    aiCrafting: "Ouverture du biscuit...",
    modalTitle: "Carte Story",
    btnClose: "Fermer",
    socialLoginLabel: "Connectez-vous pour enregistrer vos données",
    btnGoogle: "Continuer avec Google",
    btnApple: "Continuer avec Apple",
    btnSoon: "Bientôt",
    dividerOr: "ou continuer en tant qu'invité",
    labelLang: "Langue de l'application:",
    labelName: "Nom:",
    labelBirthdate: "Date de naissance:",
    labelBirthtime: "Heure de naissance:",
    labelRising: "✨ Ascendant:",
    labelSun: "☀️ Signe Solaire:",
    adVideoTitle: "🎬 Vidéo Récompensée",
    adVideoDesc: "Déblocage de l'Oracle IA 24h...",
    adTimerPrefix: "Fermeture dans",
    btnClaimReward: "🎁 Obtenir la Récompense",
    risingPrefix: "🌅 Ascendant: ",
    premiumTopLabel: "Premium",
    premiumStoreTitle: "Pass Premium",
    premiumStoreSubtitle: "Oracle IA Illimité & Thème Astral Personnalisé",
    planBadge: "🔥 Le Plus Populaire",
    planYearlyTitle: "Plan Annuel",
    planYearlyPeriod: "/an",
    planYearlyNote: "seulement $1.25 / mois",
    planMonthlyTitle: "Plan Mensuel",
    planMonthlyPeriod: "/mois",
    featUnlimited: "Oracle IA Illimité",
    featRising: "Analyse de l'Ascendant",
    featNoAds: "Expérience Sans Pub",
    featHistory: "Historique Complet",
    btnBuyYearly: "Commencer",
    btnBuyMonthly: "Plan Mensuel",
    premiumLegalText: "Renouvellement automatique. Annulable à tout moment.",
    btnWatchAdTitle: "Gagner une Oracle IA",
    btnPremiumTitle: "Passer Premium",
    btnPremiumSub: "Illimité & Sans Pub"
  },
  es: {
    appTitle: "Galleta de la Fortuna AI",
    subtitle: "¡Toca la galleta para abrirla!",
    pillText: "La magia te espera adentro",
    cardTitle: "Tu Fortuna",
    luckyTitle: "Números de la Suerte",
    btnAgain: "Otra Fortuna",
    btnStory: "Tarjeta Story",
    btnShareStory: "Compartir Story",
    shareUnavailable: "Compartir no está disponible en este dispositivo.",
    toastShared: "¡Compartido! 🌟",
    profileTitle: "Mi Perfil & Ajustes",
    historyTitle: "Historial",
    selectZodiac: "Signo Zodiacal",
    selectCategory: "Categoría:",
    namePlaceholder: "Tu nombre...",
    btnSaveProfile: "Guardar Perfil",
    btnClearHistory: "Borrar",
    noHistory: "Aún no hay historial de fortunas.",
    aiCrafting: "Abriendo la galleta...",
    modalTitle: "Tarjeta Story",
    btnClose: "Cerrar",
    socialLoginLabel: "Conéctate para guardar tus datos",
    btnGoogle: "Iniciar sesión con Google",
    btnApple: "Iniciar sesión con Apple",
    btnSoon: "Próximamente",
    dividerOr: "o continuar como invitado",
    labelLang: "Idioma de la aplicación:",
    labelName: "Nombre:",
    labelBirthdate: "Fecha de nacimiento:",
    labelBirthtime: "Hora de nacimiento:",
    labelRising: "✨ Signo Ascendente:",
    labelSun: "☀️ Signo Solar:",
    adVideoTitle: "🎬 Video de Recompensa",
    adVideoDesc: "Desbloqueando Fortunas IA por 24h...",
    adTimerPrefix: "Cerrando en",
    btnClaimReward: "🎁 Reclamar Recompensa",
    risingPrefix: "🌅 Ascendente: ",
    premiumTopLabel: "Premium",
    premiumStoreTitle: "Pase Premium",
    premiumStoreSubtitle: "Fortunas IA Ilimitadas & Astrología Personalizada",
    planBadge: "🔥 Más Popular",
    planYearlyTitle: "Plan Anual",
    planYearlyPeriod: "/año",
    planYearlyNote: "solo $1.25 / mes",
    planMonthlyTitle: "Plan Mensual",
    planMonthlyPeriod: "/mes",
    featUnlimited: "Fortunas IA Ilimitadas",
    featRising: "Análisis de Ascendente",
    featNoAds: "Experiencia Sin Anuncios",
    featHistory: "Historial Completo",
    btnBuyYearly: "Empezar Ahora",
    btnBuyMonthly: "Empezar Mensual",
    premiumLegalText: "Renovación automática. Cancela en cualquier momento.",
    btnWatchAdTitle: "Obtener Fortuna IA",
    btnPremiumTitle: "Ser Premium",
    btnPremiumSub: "Ilimitado & Sin Anuncios"
  },
  it: {
    appTitle: "Biscotto della Fortuna AI",
    subtitle: "Tocca il biscotto per aprirlo!",
    pillText: "La magia ti aspetta all'interno",
    cardTitle: "La Tua Fortuna",
    luckyTitle: "I Tuoi Numeri Fortunati",
    btnAgain: "Un Altro Biscotto",
    btnStory: "Scheda Story",
    btnShareStory: "Condividi Story",
    shareUnavailable: "La condivisione non è disponibile su questo dispositivo.",
    toastShared: "Condiviso! 🌟",
    profileTitle: "Il Mio Profilo & Impostazioni",
    historyTitle: "Cronologia",
    selectZodiac: "Segno Zodiacale",
    selectCategory: "Categoria:",
    namePlaceholder: "Il tuo nome...",
    btnSaveProfile: "Salva Profilo",
    btnClearHistory: "Cancella",
    noHistory: "Nessuna cronologia salvata.",
    aiCrafting: "Apertura del biscotto...",
    modalTitle: "Scheda Story",
    btnClose: "Chiudi",
    socialLoginLabel: "Connettiti per salvare i dati",
    btnGoogle: "Accedi con Google",
    btnApple: "Accedi con Apple",
    btnSoon: "Presto",
    dividerOr: "o continua come ospite",
    labelLang: "Lingua dell'app:",
    labelName: "Nome:",
    labelBirthdate: "Data di nascita:",
    labelBirthtime: "Ora di nascita:",
    labelRising: "✨ Ascendente:",
    labelSun: "☀️ Segno Solare:",
    adVideoTitle: "🎬 Video Premiato",
    adVideoDesc: "Sblocco Oracolo IA 24h...",
    adTimerPrefix: "Chiusura tra",
    btnClaimReward: "🎁 Riscatta Premio",
    risingPrefix: "🌅 Ascendente: ",
    premiumTopLabel: "Premium",
    premiumStoreTitle: "Pass Premium",
    premiumStoreSubtitle: "Oracoli IA Illimitati & Astrologia Personalizzata",
    planBadge: "🔥 Più Popolare",
    planYearlyTitle: "Piano Annuale",
    planYearlyPeriod: "/anno",
    planYearlyNote: "solo $1.25 / mese",
    planMonthlyTitle: "Piano Mensile",
    planMonthlyPeriod: "/mese",
    featUnlimited: "Oracoli IA Illimitati",
    featRising: "Analisi dell'Ascendente",
    featNoAds: "Esperienza Senza Pubblicità",
    featHistory: "Cronologia Completa",
    btnBuyYearly: "Inizia Ora",
    btnBuyMonthly: "Inizia Mensile",
    premiumLegalText: "Rinnovo automatico. Annulla in qualsiasi momento.",
    btnWatchAdTitle: "Ottieni Oracolo IA",
    btnPremiumTitle: "Passa a Premium",
    btnPremiumSub: "Illimitato & Senza Pub"
  },
  el: {
    appTitle: "Μπισκότο Τύχης AI",
    subtitle: "Πατήστε το μπισκότο για να το ανοίξετε!",
    pillText: "Η μαγεία σας περιμένει μέσα",
    cardTitle: "Η Τύχη Σας",
    luckyTitle: "Οι Τυχεροί Σας Αριθμοί",
    btnAgain: "Άλλο Μπισκότο",
    btnStory: "Κάρτα Story",
    btnShareStory: "Κοινοποίηση Story",
    shareUnavailable: "Η κοινοποίηση δεν είναι διαθέσιμη σε αυτήν τη συσκευή.",
    toastShared: "Κοινοποιήθηκε! 🌟",
    profileTitle: "Το Προφίλ Μου",
    historyTitle: "Ιστορικό",
    selectZodiac: "Ζώδιο",
    selectCategory: "Κατηγορία:",
    namePlaceholder: "Το όνομά σας...",
    btnSaveProfile: "Αποθήκευση Προφίλ",
    btnClearHistory: "Καθαρισμός",
    noHistory: "Δεν υπάρχει ιστορικό ακόμα.",
    aiCrafting: "Ανοίγει το μπισκότο...",
    modalTitle: "Κάρτα Story",
    btnClose: "Κλείσιμο",
    socialLoginLabel: "Συνδεθείτε για αποθήκευση",
    btnGoogle: "Σύνδεση με Google",
    btnApple: "Σύνδεση με Apple",
    btnSoon: "Σύντομα",
    dividerOr: "ή συνεχίστε ως επισκέπτης",
    labelLang: "Γλώσσα εφαρμογής:",
    labelName: "Όνομα:",
    labelBirthdate: "Ημερομηνία Γέννησης:",
    labelBirthtime: "Ώρα Γέννησης:",
    labelRising: "✨ Ωροσκόπος:",
    labelSun: "☀️ Ηλιακό Ζώδιο:",
    adVideoTitle: "🎬 Βίντεο Επιβράβευσης",
    adVideoDesc: "Ξεκλείδωμα AI Προβλέψεων 24 ωρών...",
    adTimerPrefix: "Κλείσιμο σε",
    btnClaimReward: "🎁 Παραλαβή Επιβράβευσης",
    risingPrefix: "🌅 Ωροσκόπος: ",
    premiumTopLabel: "Premium",
    premiumStoreTitle: "Πακέτο Premium",
    premiumStoreSubtitle: "Απεριόριστες Προβλέψεις AI & Αστρολογία",
    planBadge: "🔥 Δημοφιλέστερο",
    planYearlyTitle: "Ετήσιο Σχέδιο",
    planYearlyPeriod: "/έτος",
    planYearlyNote: "μόνο $1.25 / μήνα",
    planMonthlyTitle: "Μηνιαίο Σχέδιο",
    planMonthlyPeriod: "/μήνα",
    featUnlimited: "Απεριόριστες Προβλέψεις AI",
    featRising: "Ανάλυση Ωροσκόπου",
    featNoAds: "Εμπειρία Χωρίς Διαφημίσεις",
    featHistory: "Πλήρες Ιστορικό",
    btnBuyYearly: "Ξεκινήστε Τώρα",
    btnBuyMonthly: "Μηνιαίο Σχέδιο",
    premiumLegalText: "Αυτόματη ανανέωση. Ακύρωση ανά πάσα στιγμή.",
    btnWatchAdTitle: "Δωρεάν AI Πρόβλεψη",
    btnPremiumTitle: "Γίνετε Premium",
    btnPremiumSub: "Απεριόριστα & Χωρίς Διαφημίσεις"
  },
  zh: {
    appTitle: "幸运饼干 AI",
    subtitle: "点击饼干，开启幸运！",
    pillText: "魔法就在其中",
    cardTitle: "你的专属签语",
    luckyTitle: "幸运数字",
    btnAgain: "再抽一次",
    btnStory: "故事卡片",
    btnShareStory: "分享故事",
    shareUnavailable: "此设备不支持分享。",
    toastShared: "已分享！🌟",
    profileTitle: "个人资料 & 设置",
    historyTitle: "历史签语",
    selectZodiac: "选择星座",
    selectCategory: "专注领域:",
    namePlaceholder: "输入你的名字...",
    btnSaveProfile: "保存资料",
    btnClearHistory: "清空",
    noHistory: "暂无历史记录，快捏开你的第一块饼干吧！",
    aiCrafting: "正在捏开饼干...",
    modalTitle: "故事卡片生成器",
    btnClose: "关闭",
    socialLoginLabel: "绑定账号以保存数据",
    btnGoogle: "使用 Google 登录",
    btnApple: "使用 Apple 登录",
    btnSoon: "敬请期待",
    dividerOr: "或以游客身份继续",
    labelLang: "应用语言:",
    labelName: "姓名:",
    labelBirthdate: "出生日期:",
    labelBirthtime: "出生时间:",
    labelRising: "✨ 上升星座:",
    labelSun: "☀️ 太阳星座:",
    adVideoTitle: "🎬 赞助奖励视频",
    adVideoDesc: "正在解锁 24 小时 AI 签语解读...",
    adTimerPrefix: "倒计时",
    btnClaimReward: "🎁 领取奖励",
    risingPrefix: "🌅 上升: ",
    premiumTopLabel: "尊享会员",
    premiumStoreTitle: "Premium 尊享会员",
    premiumStoreSubtitle: "无限 AI 签语解读 & 专属星盘指南",
    planBadge: "🔥 最受欢迎",
    planYearlyTitle: "年度方案",
    planYearlyPeriod: "/年",
    planYearlyNote: "每月仅需 $1.25",
    planMonthlyTitle: "月度方案",
    planMonthlyPeriod: "/月",
    featUnlimited: "无限 AI 签语解读",
    featRising: "上升星座深度解析",
    featNoAds: "纯净无广告体验",
    featHistory: "完整历史签语记录",
    btnBuyYearly: "立即开启",
    btnBuyMonthly: "按月开启",
    premiumLegalText: "订阅将自动续订。可随时取消。",
    btnWatchAdTitle: "免费获取 AI 解读",
    btnPremiumTitle: "开通尊享会员",
    btnPremiumSub: "无限解读 · 无广告"
  },
  ja: {
    appTitle: "フォーチュンクッキー AI",
    subtitle: "クッキーをタップして開こう！",
    pillText: "中に魔法が待っています",
    cardTitle: "あなたの運勢",
    luckyTitle: "本日のラッキーナンバー",
    btnAgain: "もう一度ひく",
    btnStory: "ストーリーカード",
    btnShareStory: "ストーリーを共有",
    shareUnavailable: "この端末では共有を利用できません。",
    toastShared: "共有しました！ 🌟",
    profileTitle: "プロフィール & 設定",
    historyTitle: "おみくじ履歴",
    selectZodiac: "星座",
    selectCategory: "フォーカス分野:",
    namePlaceholder: "お名前を入力...",
    btnSaveProfile: "保存する",
    btnClearHistory: "消去",
    noHistory: "まだ履歴がありません。",
    aiCrafting: "クッキーを開いています...",
    modalTitle: "ストーリーカード作成",
    btnClose: "閉じる",
    socialLoginLabel: "データを保存して連携",
    btnGoogle: "Googleでログイン",
    btnApple: "Appleでログイン",
    btnSoon: "準備中",
    dividerOr: "またはゲストとして続ける",
    labelLang: "アプリ言語:",
    labelName: "お名前:",
    labelBirthdate: "生年月日:",
    labelBirthtime: "出生時間:",
    labelRising: "✨ アセンダント:",
    labelSun: "☀️ 太陽星座:",
    adVideoTitle: "🎬 リワード動画",
    adVideoDesc: "24時間AIおみくじ開放中...",
    adTimerPrefix: "終了まで:",
    btnClaimReward: "🎁 特典を受け取る",
    risingPrefix: "🌅 昇位: ",
    premiumTopLabel: "プレミアム",
    premiumStoreTitle: "プレミアムパス",
    premiumStoreSubtitle: "無制限AIおみくじ & 星座ガイド",
    planBadge: "🔥 人気ナンバーワン",
    planYearlyTitle: "年額プラン",
    planYearlyPeriod: "/年",
    planYearlyNote: "月額たったの $1.25",
    planMonthlyTitle: "月額プラン",
    planMonthlyPeriod: "/月",
    featUnlimited: "無制限AIおみくじ",
    featRising: "アセンダント深度分析",
    featNoAds: "広告なしで快適",
    featHistory: "全おみくじ履歴",
    btnBuyYearly: "今すぐ始める",
    btnBuyMonthly: "月額で始める",
    premiumLegalText: "自動更新サブスクリプション。いつでもキャンセル可能。",
    btnWatchAdTitle: "無料AIおみくじ獲得",
    btnPremiumTitle: "プレミアム登録",
    btnPremiumSub: "無制限 & 広告非表示"
  },
  ko: {
    appTitle: "포춘쿠키 AI",
    subtitle: "쿠키를 터치하여 열어보세요!",
    pillText: "마법이 당신을 기다립니다",
    cardTitle: "오늘의 운세",
    luckyTitle: "오늘의 행운의 숫자",
    btnAgain: "다시 뽑기",
    btnStory: "스토리 카드",
    btnShareStory: "스토리 공유",
    shareUnavailable: "이 기기에서는 공유를 사용할 수 없습니다.",
    toastShared: "공유되었습니다! 🌟",
    profileTitle: "내 프로필 & 설정",
    historyTitle: "운세 히스토리",
    selectZodiac: "별자리",
    selectCategory: "관심 분야:",
    namePlaceholder: "이름을 입력하세요...",
    btnSaveProfile: "프로필 저장",
    btnClearHistory: "지우기",
    noHistory: "저장된 히스토리가 없습니다.",
    aiCrafting: "포춘쿠키를 여는 중...",
    modalTitle: "스토리 카드 생성기",
    btnClose: "닫기",
    socialLoginLabel: "데이터 보존을 위해 로그인",
    btnGoogle: "Google 계정으로 로그인",
    btnApple: "Apple 계정으로 로그인",
    btnSoon: "출시 예정",
    dividerOr: "또는 게스트로 계속하기",
    labelLang: "앱 언어:",
    labelName: "이름:",
    labelBirthdate: "생년월일:",
    labelBirthtime: "출생시간:",
    labelRising: "✨ 상승궁:",
    labelSun: "☀️ 태양궁:",
    adVideoTitle: "🎬 보상형 동영상",
    adVideoDesc: "24시간 무제한 AI 운세 해금 중...",
    adTimerPrefix: "남은 시간:",
    btnClaimReward: "🎁 보상 받기",
    risingPrefix: "🌅 상승궁: ",
    premiumTopLabel: "프리미엄",
    premiumStoreTitle: "프리미엄 패스",
    premiumStoreSubtitle: "무제한 AI 운세 & 맞춤 별자리 가이드",
    planBadge: "🔥 가장 인기",
    planYearlyTitle: "연간 플랜",
    planYearlyPeriod: "/년",
    planYearlyNote: "월 단 $1.25",
    planMonthlyTitle: "월간 플랜",
    planMonthlyPeriod: "/월",
    featUnlimited: "무제한 AI 운세",
    featRising: "상승궁 상세 분석",
    featNoAds: "광고 없는 클린 체험",
    featHistory: "전체 운세 히스토리",
    btnBuyYearly: "지금 시작하기",
    btnBuyMonthly: "월간 시작",
    premiumLegalText: "구독은 자동 갱신됩니다. 언제든 취소 가능.",
    btnWatchAdTitle: "무료 AI 운세 받기",
    btnPremiumTitle: "프리미엄 가입",
    btnPremiumSub: "무제한 & 무광고"
  }
};
