export const SUPPORTED_LANGUAGES = ['tr', 'en', 'de', 'fr', 'es', 'it', 'el', 'zh', 'ja', 'ko'];

const rows = {
  historyDeleteTitle: ['Şans Kurabiyesi geçmişini temizle','Clear Fortune Cookie history','Glückskeks-Verlauf löschen','Effacer l’historique des Fortune Cookies','Borrar el historial de galletas de la fortuna','Cancella la cronologia dei biscotti della fortuna','Εκκαθάριση ιστορικού μπισκότων τύχης','清除幸运饼干历史','フォーチュンクッキー履歴を消去','포춘 쿠키 기록 지우기'],
  historyDeleteDesc: ['Kaydettiğin Şans Kurabiyeleri cihazdan ve hesabından silinir.','Your saved Fortune Cookies will be removed from this device and your account.','Gespeicherte Glückskekse werden vom Gerät und aus deinem Konto entfernt.','Vos Fortune Cookies enregistrés seront supprimés de l’appareil et du compte.','Tus galletas guardadas se eliminarán del dispositivo y de tu cuenta.','I biscotti salvati verranno rimossi dal dispositivo e dall’account.','Τα αποθηκευμένα μπισκότα τύχης θα αφαιρεθούν από τη συσκευή και τον λογαριασμό.','已保存的幸运饼干将从设备和账户中删除。','保存したフォーチュンクッキーを端末とアカウントから削除します。','저장된 포춘 쿠키가 기기와 계정에서 삭제됩니다.'],
  historyDeleteButton: ['Geçmişi temizle','Clear history','Verlauf löschen','Effacer l’historique','Borrar historial','Cancella cronologia','Εκκαθάριση ιστορικού','清除历史','履歴を消去','기록 지우기'],
  historyDeleteConfirmTitle: ['Şans Kurabiyesi geçmişi temizlensin mi?','Clear your Fortune Cookie history?','Glückskeks-Verlauf löschen?','Effacer votre historique de Fortune Cookies ?','¿Borrar tu historial de galletas de la fortuna?','Cancellare la cronologia dei biscotti della fortuna?','Να εκκαθαριστεί το ιστορικό μπισκότων τύχης;','清除幸运饼干历史？','フォーチュンクッキー履歴を消去しますか？','포춘 쿠키 기록을 지울까요?'],
  historyDeleteConfirmBody: ['Kaydettiğin tüm Şans Kurabiyeleri cihazdan ve buluttan silinecek. Bu işlem geri alınamaz.','All saved Fortune Cookies will be deleted from the device and cloud. This cannot be undone.','Alle gespeicherten Glückskekse werden vom Gerät und aus der Cloud gelöscht. Dies kann nicht rückgängig gemacht werden.','Tous les Fortune Cookies enregistrés seront supprimés de l’appareil et du cloud. Cette action est irréversible.','Todas las galletas guardadas se eliminarán del dispositivo y de la nube. Esta acción no se puede deshacer.','Tutti i biscotti salvati verranno eliminati dal dispositivo e dal cloud. L’azione è irreversibile.','Όλα τα αποθηκευμένα μπισκότα τύχης θα διαγραφούν από τη συσκευή και το cloud. Η ενέργεια δεν αναιρείται.','所有保存的幸运饼干都将从设备和云端删除。此操作无法撤销。','保存したすべてのフォーチュンクッキーを端末とクラウドから削除します。この操作は取り消せません。','저장된 모든 포춘 쿠키가 기기와 클라우드에서 삭제되며 되돌릴 수 없습니다.'],
  historyDeleteConfirm: ['Evet, geçmişi temizle','Yes, clear history','Ja, Verlauf löschen','Oui, effacer l’historique','Sí, borrar historial','Sì, cancella la cronologia','Ναι, εκκαθάριση','是，清除历史','はい、履歴を消去','예, 기록 지우기'],
  historyDeleteSuccess: ['Şans Kurabiyesi geçmişin temizlendi.','Your Fortune Cookie history was cleared.','Dein Glückskeks-Verlauf wurde gelöscht.','Votre historique de Fortune Cookies a été effacé.','Tu historial de galletas de la fortuna se borró.','La cronologia dei biscotti della fortuna è stata cancellata.','Το ιστορικό μπισκότων τύχης εκκαθαρίστηκε.','幸运饼干历史已清除。','フォーチュンクッキー履歴を消去しました。','포춘 쿠키 기록을 지웠습니다.'],
  historyDeleteError: ['Geçmiş temizlenemedi. Bağlantını kontrol edip tekrar dene.','History could not be cleared. Check your connection and try again.','Der Verlauf konnte nicht gelöscht werden. Prüfe die Verbindung und versuche es erneut.','Impossible d’effacer l’historique. Vérifiez votre connexion et réessayez.','No se pudo borrar el historial. Comprueba tu conexión e inténtalo de nuevo.','Impossibile cancellare la cronologia. Controlla la connessione e riprova.','Δεν ήταν δυνατή η εκκαθάριση. Ελέγξτε τη σύνδεση και δοκιμάστε ξανά.','无法清除历史。请检查网络后重试。','履歴を消去できませんでした。接続を確認して再試行してください。','기록을 지우지 못했습니다. 연결을 확인하고 다시 시도하세요.'],
  clearing: ['Temizleniyor…','Clearing…','Wird gelöscht…','Effacement…','Borrando…','Cancellazione…','Εκκαθάριση…','正在清除…','消去中…','지우는 중…'],
  appTitle: ['Şans Kurabiyesi AI','Fortune Cookie AI','Glückskeks AI','Fortune Cookie IA','Galleta de la Fortuna IA','Biscotto della Fortuna AI','Μπισκότο Τύχης AI','AI 幸运饼干','フォーチュンクッキー AI','포춘 쿠키 AI'],
  paperText: ['✨ ŞANS KURABİYESİ','✨ FORTUNE COOKIE','✨ GLÜCKSKEKS','✨ FORTUNE COOKIE','✨ GALLETA DE LA FORTUNA','✨ BISCOTTO DELLA FORTUNA','✨ ΜΠΙΣΚΟΤΟ ΤΥΧΗΣ','✨ 幸运饼干','✨ フォーチュンクッキー','✨ 포춘 쿠키'],
  personalPaperText: ['✨ KİŞİSEL ŞANS KURABİYESİ','✨ PERSONAL FORTUNE COOKIE','✨ PERSÖNLICHER GLÜCKSKEKS','✨ FORTUNE COOKIE PERSONNALISÉ','✨ GALLETA PERSONALIZADA','✨ BISCOTTO PERSONALE','✨ ΠΡΟΣΩΠΙΚΟ ΜΠΙΣΚΟΤΟ ΤΥΧΗΣ','✨ 个性化幸运饼干','✨ パーソナルフォーチュンクッキー','✨ 맞춤 포춘 쿠키'],
  cookieAria: ['Şans kurabiyesini kırmak için dokunun','Tap to crack the Fortune Cookie','Tippen, um den Glückskeks zu öffnen','Touchez pour ouvrir le Fortune Cookie','Toca para abrir la galleta de la fortuna','Tocca per aprire il biscotto della fortuna','Αγγίξτε για να ανοίξετε το μπισκότο τύχης','点击打开幸运饼干','タップしてフォーチュンクッキーを開く','탭하여 포춘 쿠키 열기'],
  cardTitle: ['Senin Şans Kurabiyen','Your Fortune Cookie','Dein Glückskeks','Votre Fortune Cookie','Tu galleta de la fortuna','Il tuo biscotto della fortuna','Το μπισκότο τύχης σου','你的幸运饼干','あなたのフォーチュンクッキー','나의 포춘 쿠키'],
  luckyTitle: ['Günün Şanslı Sayıları','Today’s Lucky Numbers','Heutige Glückszahlen','Numéros chanceux du jour','Números de la suerte de hoy','Numeri fortunati di oggi','Τυχεροί αριθμοί της ημέρας','今日幸运数字','今日のラッキーナンバー','오늘의 행운 숫자'],
  again: ['Yeniden Başla','Open another','Neuen Keks öffnen','Ouvrir un autre','Abrir otra','Aprine un altro','Άνοιξε άλλο','再开一个','もう一度開く','다시 열기'],
  storyCard: ['Hikaye Kartı','Story Card','Story-Karte','Carte Story','Tarjeta de historia','Scheda storia','Κάρτα Story','故事卡片','ストーリーカード','스토리 카드'],
  shareStory: ['Hikayeyi Paylaş','Share Story','Story teilen','Partager la Story','Compartir historia','Condividi storia','Κοινοποίηση Story','分享故事','ストーリーを共有','스토리 공유'],
  bootstrapTitle: ['Uygulama hazırlanıyor','Preparing the app','App wird vorbereitet','Préparation de l’application','Preparando la aplicación','Preparazione dell’app','Προετοιμασία εφαρμογής','正在准备应用','アプリを準備しています','앱을 준비하고 있습니다'],
  bootstrapSession: ['Güvenli oturum kuruluyor…','Setting up a secure session…','Sichere Sitzung wird eingerichtet…','Création d’une session sécurisée…','Configurando una sesión segura…','Configurazione della sessione sicura…','Δημιουργία ασφαλούς συνεδρίας…','正在建立安全会话…','安全なセッションを設定中…','보안 세션 설정 중…'],
  bootstrapServices: ['Hesabınız ve servisler hazırlanıyor…','Preparing your account and services…','Konto und Dienste werden vorbereitet…','Préparation du compte et des services…','Preparando tu cuenta y los servicios…','Preparazione di account e servizi…','Προετοιμασία λογαριασμού και υπηρεσιών…','正在准备账户和服务…','アカウントとサービスを準備中…','계정과 서비스를 준비 중…'],
  bootstrapSettings: ['Ayarlarınız yükleniyor…','Loading your settings…','Einstellungen werden geladen…','Chargement de vos réglages…','Cargando tus ajustes…','Caricamento delle impostazioni…','Φόρτωση ρυθμίσεων…','正在加载设置…','設定を読み込み中…','설정을 불러오는 중…'],
  profilePersonalTitle: ['Kişisel Bilgiler','Personal details','Persönliche Angaben','Informations personnelles','Datos personales','Dati personali','Προσωπικά στοιχεία','个人信息','個人情報','개인 정보'],
  profilePersonalDesc: ['Şans Kurabiyesi deneyimini sana göre kişiselleştir.','Personalize your Fortune Cookie experience.','Personalisiere dein Glückskeks-Erlebnis.','Personnalisez votre expérience Fortune Cookie.','Personaliza tu experiencia de galleta de la fortuna.','Personalizza la tua esperienza con il biscotto della fortuna.','Εξατομίκευσε την εμπειρία του μπισκότου τύχης.','个性化你的幸运饼干体验。','フォーチュンクッキー体験を自分好みに。','포춘 쿠키 경험을 맞춤 설정하세요.'],
  name: ['İsim','Name','Name','Nom','Nombre','Nome','Όνομα','姓名','名前','이름'],
  language: ['Uygulama Dili','App language','App-Sprache','Langue de l’application','Idioma de la aplicación','Lingua dell’app','Γλώσσα εφαρμογής','应用语言','アプリの言語','앱 언어'],
  birthChartTitle: ['Doğum Haritası','Birth chart','Geburtshoroskop','Thème natal','Carta natal','Tema natale','Γενέθλιος χάρτης','出生星盘','出生図','출생 차트'],
  birthChartDesc: ['Yükselen burç için tarih, saat ve doğum yeri gerekir.','Date, time and birthplace are required for the rising sign.','Für den Aszendenten sind Datum, Uhrzeit und Geburtsort erforderlich.','La date, l’heure et le lieu de naissance sont requis pour l’ascendant.','Se necesitan fecha, hora y lugar de nacimiento para el ascendente.','Per l’ascendente servono data, ora e luogo di nascita.','Για τον ωροσκόπο απαιτούνται ημερομηνία, ώρα και τόπος γέννησης.','计算上升星座需要出生日期、时间和地点。','アセンダントには生年月日・時刻・出生地が必要です。','상승궁 계산에는 생년월일, 시간, 출생지가 필요합니다.'],
  birthplace: ['Doğum Yeri','Birthplace','Geburtsort','Lieu de naissance','Lugar de nacimiento','Luogo di nascita','Τόπος γέννησης','出生地','出生地','출생지'],
  coordinatesAuto: ['Koordinatlar otomatik bulunur','Coordinates are found automatically','Koordinaten werden automatisch ermittelt','Les coordonnées sont trouvées automatiquement','Las coordenadas se obtienen automáticamente','Le coordinate vengono trovate automaticamente','Οι συντεταγμένες εντοπίζονται αυτόματα','自动查找坐标','座標は自動検索されます','좌표를 자동으로 찾습니다'],
  country: ['Ülke','Country','Land','Pays','País','Paese','Χώρα','国家/地区','国','국가'],
  city: ['Şehir / İl','City / State','Stadt / Bundesland','Ville / Région','Ciudad / Provincia','Città / Provincia','Πόλη / Περιφέρεια','城市 / 省份','市区町村 / 都道府県','도시 / 시·도'],
  region: ['İlçe / Bölge','District / Region','Bezirk / Region','District / Région','Distrito / Región','Distretto / Regione','Περιοχή / Περιφέρεια','区县 / 地区','区 / 地域','구 / 지역'],
  resolveLocation: ['Konumu Bul ve Saat Dilimini Doldur','Find location and fill time zone','Ort und Zeitzone ermitteln','Trouver le lieu et le fuseau horaire','Buscar ubicación y completar zona horaria','Trova luogo e fuso orario','Εύρεση τοποθεσίας και ζώνης ώρας','查找地点并填写时区','場所を検索してタイムゾーンを入力','위치와 시간대 찾기'],
  advancedLocation: ['Gelişmiş konum bilgileri','Advanced location details','Erweiterte Ortsangaben','Détails avancés du lieu','Datos avanzados de ubicación','Dettagli avanzati della località','Σύνθετα στοιχεία τοποθεσίας','高级位置信息','詳細な位置情報','고급 위치 정보'],
  latitude: ['Enlem','Latitude','Breitengrad','Latitude','Latitud','Latitudine','Γεωγραφικό πλάτος','纬度','緯度','위도'],
  longitude: ['Boylam','Longitude','Längengrad','Longitude','Longitud','Longitudine','Γεωγραφικό μήκος','经度','経度','경도'],
  utcAtBirth: ['Doğumdaki UTC','UTC at birth','UTC bei Geburt','UTC à la naissance','UTC al nacer','UTC alla nascita','UTC κατά τη γέννηση','出生时 UTC','出生時のUTC','출생 당시 UTC'],
  risingKnown: ['Yükselen burcumu zaten biliyorum','I already know my rising sign','Ich kenne meinen Aszendenten','Je connais déjà mon ascendant','Ya conozco mi ascendente','Conosco già il mio ascendente','Γνωρίζω ήδη τον ωροσκόπο μου','我已知道自己的上升星座','自分のアセンダントを知っています','내 상승궁을 알고 있습니다'],
  chooseRising: ['Yükselen burç seçin','Choose a rising sign','Aszendent wählen','Choisir un ascendant','Elegir ascendente','Scegli l’ascendente','Επιλέξτε ωροσκόπο','选择上升星座','アセンダントを選択','상승궁 선택'],
  focusTitle: ['Şans Kurabiyesi Odağı','Fortune Cookie focus','Glückskeks-Fokus','Thème du Fortune Cookie','Enfoque de la galleta','Tema del biscotto','Εστίαση μπισκότου τύχης','幸运饼干主题','フォーチュンクッキーのテーマ','포춘 쿠키 주제'],
  focusDesc: ['Bugün hangi alana odaklanalım?','What should we focus on today?','Worauf sollen wir uns heute konzentrieren?','Quel thème souhaitez-vous aujourd’hui ?','¿En qué nos centramos hoy?','Su cosa ci concentriamo oggi?','Σε τι να εστιάσουμε σήμερα;','今天想关注哪个方面？','今日は何に目を向けますか？','오늘 어떤 주제에 집중할까요?'],
  deleteTitle: ['Hesabımı ve verilerimi sil','Delete my account and data','Konto und Daten löschen','Supprimer mon compte et mes données','Eliminar mi cuenta y mis datos','Elimina account e dati','Διαγραφή λογαριασμού και δεδομένων','删除账户和数据','アカウントとデータを削除','계정 및 데이터 삭제'],
  deleteDesc: ['Profilin, Şans Kurabiyesi geçmişin ve kullanım kayıtların kalıcı olarak silinir.','Your profile, Fortune Cookie history and usage records will be permanently deleted.','Profil, Glückskeks-Verlauf und Nutzungsdaten werden dauerhaft gelöscht.','Votre profil, votre historique et vos données d’utilisation seront définitivement supprimés.','Tu perfil, historial y registros de uso se eliminarán definitivamente.','Profilo, cronologia e dati di utilizzo saranno eliminati definitivamente.','Το προφίλ, το ιστορικό και οι εγγραφές χρήσης θα διαγραφούν οριστικά.','个人资料、幸运饼干历史和使用记录将被永久删除。','プロフィール、履歴、利用記録は完全に削除されます。','프로필, 포춘 쿠키 기록 및 사용 기록이 영구 삭제됩니다.'],
  usage: ['Bugün {used}/{limit} kullanıldı · {remaining} hak kaldı','Used {used}/{limit} today · {remaining} left','Heute {used}/{limit} genutzt · {remaining} übrig','{used}/{limit} utilisés aujourd’hui · {remaining} restants','Hoy {used}/{limit} usados · quedan {remaining}','Oggi {used}/{limit} usati · {remaining} rimasti','Σήμερα {used}/{limit} · απομένουν {remaining}','今日已用 {used}/{limit} · 剩余 {remaining}','本日 {used}/{limit} 回使用 · 残り {remaining}','오늘 {used}/{limit}회 사용 · {remaining}회 남음'],
  premiumActive: ['Premium AI aktif · Günlük {limit} hak','Premium AI active · {limit} daily uses','Premium AI aktiv · {limit} täglich','IA Premium active · {limit} utilisations/jour','IA Premium activa · {limit} usos diarios','AI Premium attiva · {limit} usi giornalieri','Premium AI ενεργό · {limit} ημερησίως','高级 AI 已启用 · 每日 {limit} 次','プレミアムAI有効 · 1日{limit}回','프리미엄 AI 활성 · 일일 {limit}회'],
  watchAd: ['Premium AI Şans Kurabiyesi için reklam izle','Watch an ad for a Premium AI Fortune Cookie','Werbung für einen Premium-AI-Glückskeks ansehen','Regarder une publicité pour un Fortune Cookie IA Premium','Ver un anuncio para una galleta IA Premium','Guarda un annuncio per un biscotto AI Premium','Δείτε διαφήμιση για Premium AI μπισκότο τύχης','观看广告获取高级 AI 幸运饼干','広告を見てプレミアムAIフォーチュンクッキーを獲得','광고를 보고 프리미엄 AI 포춘 쿠키 받기'],
  adProgress: ['Reklamlar: {current}/{required}','Ads: {current}/{required}','Werbung: {current}/{required}','Publicités : {current}/{required}','Anuncios: {current}/{required}','Annunci: {current}/{required}','Διαφημίσεις: {current}/{required}','广告：{current}/{required}','広告：{current}/{required}','광고: {current}/{required}'],
  adVerifiedProgress: ['Reklam doğrulandı · {current}/{required}','Ad verified · {current}/{required}','Werbung bestätigt · {current}/{required}','Publicité vérifiée · {current}/{required}','Anuncio verificado · {current}/{required}','Annuncio verificato · {current}/{required}','Η διαφήμιση επαληθεύτηκε · {current}/{required}','广告已验证 · {current}/{required}','広告を確認しました · {current}/{required}','광고 확인 완료 · {current}/{required}'],
  adVerificationPending: ['Reklam tamamlandı. Ödül doğrulaması kısa süre içinde hesabına yansıyacak.','Ad completed. Reward verification will appear in your account shortly.','Werbung abgeschlossen. Die Bestätigung wird deinem Konto in Kürze gutgeschrieben.','Publicité terminée. La vérification apparaîtra bientôt sur votre compte.','Anuncio completado. La verificación aparecerá pronto en tu cuenta.','Annuncio completato. La verifica apparirà a breve sul tuo account.','Η διαφήμιση ολοκληρώθηκε. Η επαλήθευση θα εμφανιστεί σύντομα στον λογαριασμό σας.','广告已完成，奖励验证很快会显示在你的账户中。','広告は完了しました。報酬の確認はまもなくアカウントに反映されます。','광고를 완료했습니다. 보상 확인 결과가 곧 계정에 반영됩니다.'],
  adCreditGranted: ['🎁 Reklam tamamlandı · Premium Şans Kurabiyen hazır!','🎁 Ad completed · Your Premium Fortune Cookie is ready!','🎁 Werbung abgeschlossen · Dein Premium-Glückskeks ist bereit!','🎁 Publicité terminée · Votre Fortune Cookie Premium est prêt !','🎁 Anuncio completado · ¡Tu galleta Premium está lista!','🎁 Annuncio completato · Il tuo biscotto Premium è pronto!','🎁 Η διαφήμιση ολοκληρώθηκε · Το Premium μπισκότο είναι έτοιμο!','🎁 广告已完成 · 高级幸运饼干已准备好！','🎁 広告が完了しました · プレミアムフォーチュンクッキーの準備完了！','🎁 광고 완료 · 프리미엄 포춘 쿠키가 준비됐어요!'],
  adUnavailable: ['Reklam şu anda yüklenemedi. Lütfen biraz sonra yeniden deneyin.','The ad could not be loaded. Please try again shortly.','Die Werbung konnte nicht geladen werden. Bitte versuche es gleich noch einmal.','La publicité n’a pas pu être chargée. Réessayez dans un instant.','No se pudo cargar el anuncio. Inténtalo de nuevo en unos instantes.','Impossibile caricare l’annuncio. Riprova tra poco.','Η διαφήμιση δεν φορτώθηκε. Δοκιμάστε ξανά σε λίγο.','广告暂时无法加载，请稍后重试。','広告を読み込めませんでした。しばらくしてから再試行してください。','광고를 불러오지 못했습니다. 잠시 후 다시 시도해 주세요.'],
  aiReady: ['Premium AI hazır','Premium AI ready','Premium AI bereit','IA Premium prête','IA Premium lista','AI Premium pronta','Premium AI έτοιμο','高级 AI 已就绪','プレミアムAI準備完了','프리미엄 AI 준비 완료'],
  rightsAvailable: ['{count} hak mevcut','{count} available','{count} verfügbar','{count} disponible(s)','{count} disponible(s)','{count} disponibili','{count} διαθέσιμα','可用 {count} 次','残り {count} 回','{count}회 사용 가능'],
  locked: ['Kilitli','Locked','Gesperrt','Verrouillé','Bloqueado','Bloccato','Κλειδωμένο','已锁定','ロック中','잠김'],
  accountFree: ['Ücretsiz Üye','Free member','Kostenloses Mitglied','Membre gratuit','Miembro gratuito','Utente gratuito','Δωρεάν μέλος','免费会员','無料会員','무료 회원'],
  accountPremium: ['Premium AI Üye','Premium AI member','Premium-AI-Mitglied','Membre IA Premium','Miembro IA Premium','Utente AI Premium','Μέλος Premium AI','高级 AI 会员','プレミアムAI会員','프리미엄 AI 회원'],
  freeAllowance: ['Günlük {limit} Şans Kurabiyesi hakkı','{limit} Fortune Cookie per day','{limit} Glückskeks pro Tag','{limit} Fortune Cookie par jour','{limit} galleta de la fortuna al día','{limit} biscotto della fortuna al giorno','{limit} μπισκότο τύχης την ημέρα','每天 {limit} 个幸运饼干','1日{limit}個のフォーチュンクッキー','하루 포춘 쿠키 {limit}개'],
  premiumAllowance: ['Günlük {limit} Premium AI Şans Kurabiyesi ve reklamsız deneyim','{limit} Premium AI Fortune Cookies daily and no ads','{limit} Premium-AI-Glückskekse täglich und werbefrei','{limit} Fortune Cookies IA Premium par jour, sans publicité','{limit} galletas IA Premium al día y sin anuncios','{limit} biscotti AI Premium al giorno e senza pubblicità','{limit} Premium AI μπισκότα ημερησίως, χωρίς διαφημίσεις','每日 {limit} 个高级 AI 幸运饼干，无广告','1日{limit}個のプレミアムAIフォーチュンクッキー・広告なし','매일 프리미엄 AI 포춘 쿠키 {limit}개, 광고 없음'],
  premiumDailyFeature: ['Günlük {limit} Premium AI Şans Kurabiyesi','{limit} Premium AI Fortune Cookies daily','{limit} Premium-AI-Glückskekse täglich','{limit} Fortune Cookies IA Premium par jour','{limit} galletas IA Premium al día','{limit} biscotti AI Premium al giorno','{limit} Premium AI μπισκότα ημερησίως','每日 {limit} 个高级 AI 幸运饼干','1日{limit}個のプレミアムAIフォーチュンクッキー','매일 프리미엄 AI 포춘 쿠키 {limit}개'],
  firstCrack: ['İlk çatlak oluştu · 2 dokunuş kaldı','First crack · 2 taps left','Erster Riss · noch 2-mal tippen','Première fissure · encore 2 touchers','Primera grieta · faltan 2 toques','Prima crepa · mancano 2 tocchi','Πρώτη ρωγμή · 2 αγγίγματα ακόμη','第一道裂纹 · 还需点击 2 次','最初のひび · あと2回','첫 번째 금 · 2번 남음'],
  secondCrack: ['Kurabiye çatlıyor · 1 dokunuş kaldı','The cookie is cracking · 1 tap left','Der Keks bricht · noch 1-mal tippen','Le biscuit se fissure · encore 1 toucher','La galleta se rompe · falta 1 toque','Il biscotto si rompe · manca 1 tocco','Το μπισκότο σπάει · 1 άγγιγμα ακόμη','饼干正在裂开 · 还需点击 1 次','クッキーが割れます · あと1回','쿠키가 갈라지는 중 · 1번 남음'],
  preparingFortune: ['Şans Kurabiyen hazırlanıyor…','Your Fortune Cookie is being prepared…','Dein Glückskeks wird vorbereitet…','Votre Fortune Cookie est en préparation…','Tu galleta de la fortuna se está preparando…','Il tuo biscotto della fortuna è in preparazione…','Το μπισκότο τύχης ετοιμάζεται…','正在准备你的幸运饼干…','フォーチュンクッキーを準備中…','포춘 쿠키를 준비 중…'],
  imageNotReady: ['Görsel henüz hazır değil.','The image is not ready yet.','Das Bild ist noch nicht bereit.','L’image n’est pas encore prête.','La imagen aún no está lista.','L’immagine non è ancora pronta.','Η εικόνα δεν είναι ακόμη έτοιμη.','图片尚未准备好。','画像はまだ準備できていません。','이미지가 아직 준비되지 않았습니다.'],
  saved: ['Profil kaydedildi!','Profile saved!','Profil gespeichert!','Profil enregistré !','¡Perfil guardado!','Profilo salvato!','Το προφίλ αποθηκεύτηκε!','个人资料已保存！','プロフィールを保存しました！','프로필이 저장되었습니다!']
  ,locationPrompt: ['Ülke ve şehir girerek doğum yerini doğrulayın.','Enter a country and city to verify the birthplace.','Land und Stadt eingeben, um den Geburtsort zu prüfen.','Saisissez le pays et la ville pour vérifier le lieu de naissance.','Introduce país y ciudad para verificar el lugar de nacimiento.','Inserisci paese e città per verificare il luogo di nascita.','Εισαγάγετε χώρα και πόλη για επαλήθευση.','输入国家和城市以验证出生地。','国と市区町村を入力して出生地を確認してください。','국가와 도시를 입력해 출생지를 확인하세요.'],
  locationAttribution: ['Konum verisi © OpenStreetMap katkıcıları','Location data © OpenStreetMap contributors','Ortsdaten © OpenStreetMap-Mitwirkende','Données géographiques © contributeurs OpenStreetMap','Datos de ubicación © colaboradores de OpenStreetMap','Dati geografici © collaboratori OpenStreetMap','Δεδομένα τοποθεσίας © συνεισφέροντες OpenStreetMap','位置数据 © OpenStreetMap 贡献者','位置情報 © OpenStreetMap contributors','위치 데이터 © OpenStreetMap 기여자'],
  upgrade: ['Premium AI’a yükselt','Upgrade to Premium AI','Auf Premium AI upgraden','Passer à l’IA Premium','Mejorar a IA Premium','Passa a AI Premium','Αναβάθμιση σε Premium AI','升级到高级 AI','プレミアムAIにアップグレード','프리미엄 AI로 업그레이드'],
  premiumEnabled: ['Premium AI aktif','Premium AI active','Premium AI aktiv','IA Premium active','IA Premium activa','AI Premium attiva','Premium AI ενεργό','高级 AI 已启用','プレミアムAI有効','프리미엄 AI 활성']
  ,emailAuthTitle: ['E-posta ile devam et','Continue with email','Mit E-Mail fortfahren','Continuer avec l’e-mail','Continuar con correo','Continua con e-mail','Συνέχεια με email','使用电子邮件继续','メールで続ける','이메일로 계속'],
  emailNameLabel: ['Adınız (kayıt için)','Name (for registration)','Name (für Registrierung)','Nom (pour l’inscription)','Nombre (para registro)','Nome (per registrazione)','Όνομα (για εγγραφή)','姓名（用于注册）','名前（登録用）','이름(가입용)'],
  emailNamePlaceholder: ['Adınız','Your name','Ihr Name','Votre nom','Tu nombre','Il tuo nome','Το όνομά σας','您的姓名','お名前','이름'],
  emailLabel: ['E-posta','Email','E-Mail','E-mail','Correo electrónico','E-mail','Email','电子邮件','メール','이메일'],
  passwordLabel: ['Şifre','Password','Passwort','Mot de passe','Contraseña','Password','Κωδικός','密码','パスワード','비밀번호'],
  passwordPlaceholder: ['En az 8 karakter','At least 8 characters','Mindestens 8 Zeichen','Au moins 8 caractères','Mínimo 8 caracteres','Almeno 8 caratteri','Τουλάχιστον 8 χαρακτήρες','至少 8 个字符','8文字以上','8자 이상'],
  emailLogin: ['Giriş yap','Sign in','Anmelden','Se connecter','Iniciar sesión','Accedi','Σύνδεση','登录','ログイン','로그인'],
  emailRegister: ['Hesap oluştur','Create account','Konto erstellen','Créer un compte','Crear cuenta','Crea account','Δημιουργία λογαριασμού','创建账户','アカウント作成','계정 만들기'],
  emailReset: ['Şifremi unuttum','Forgot password','Passwort vergessen','Mot de passe oublié','Olvidé mi contraseña','Password dimenticata','Ξέχασα τον κωδικό','忘记密码','パスワードを忘れた','비밀번호 찾기'],
  emailConnected: ['E-posta ile bağlı','Connected with email','Mit E-Mail verbunden','Connecté par e-mail','Conectado con correo','Collegato con e-mail','Συνδεδεμένο με email','已通过电子邮件连接','メールで連携済み','이메일 연결됨'],
  emailVerificationSent: ['Doğrulama bağlantısını e-postanıza gönderdik. Doğruladıktan sonra giriş yapın.','We sent a verification link to your email. Verify it, then sign in.','Wir haben einen Bestätigungslink gesendet. Bestätigen Sie ihn und melden Sie sich an.','Un lien de vérification a été envoyé. Vérifiez-le, puis connectez-vous.','Enviamos un enlace de verificación. Verifícalo y luego inicia sesión.','Abbiamo inviato un link di verifica. Verificalo, poi accedi.','Στείλαμε σύνδεσμο επαλήθευσης. Επιβεβαιώστε τον και συνδεθείτε.','验证链接已发送。验证后请登录。','確認リンクを送信しました。確認後にログインしてください。','인증 링크를 보냈습니다. 인증 후 로그인하세요.'],
  emailVerificationRequired: ['Önce e-posta adresinizi doğrulayın. Yeni doğrulama bağlantısı gönderildi.','Verify your email first. A new verification link was sent.','Bestätigen Sie zuerst Ihre E-Mail. Ein neuer Link wurde gesendet.','Vérifiez d’abord votre e-mail. Un nouveau lien a été envoyé.','Primero verifica tu correo. Se envió un enlace nuevo.','Verifica prima l’e-mail. È stato inviato un nuovo link.','Επαληθεύστε πρώτα το email. Στάλθηκε νέος σύνδεσμος.','请先验证电子邮件。新的验证链接已发送。','先にメールを確認してください。新しいリンクを送信しました。','이메일을 먼저 인증하세요. 새 인증 링크를 보냈습니다.'],
  emailResetSent: ['Bu adres kayıtlıysa şifre sıfırlama bağlantısı gönderildi.','If this address is registered, a password reset link was sent.','Falls die Adresse registriert ist, wurde ein Link zum Zurücksetzen gesendet.','Si cette adresse est inscrite, un lien de réinitialisation a été envoyé.','Si la dirección está registrada, se envió un enlace para restablecerla.','Se l’indirizzo è registrato, è stato inviato un link di ripristino.','Αν η διεύθυνση είναι καταχωρισμένη, στάλθηκε σύνδεσμος επαναφοράς.','如果该地址已注册，密码重置链接已发送。','登録済みの場合、リセットリンクを送信しました。','등록된 주소라면 재설정 링크를 보냈습니다.'],
  emailInvalidFields: ['Geçerli e-posta ve en az 8 karakterlik şifre girin.','Enter a valid email and a password of at least 8 characters.','Geben Sie eine gültige E-Mail und mindestens 8 Zeichen ein.','Saisissez un e-mail valide et un mot de passe d’au moins 8 caractères.','Introduce un correo válido y una contraseña de al menos 8 caracteres.','Inserisci un’e-mail valida e una password di almeno 8 caratteri.','Εισαγάγετε έγκυρο email και κωδικό τουλάχιστον 8 χαρακτήρων.','请输入有效邮箱和至少 8 个字符的密码。','有効なメールと8文字以上のパスワードを入力してください。','올바른 이메일과 8자 이상의 비밀번호를 입력하세요.'],
  emailAuthBusy: ['İşlem yapılıyor…','Please wait…','Bitte warten…','Veuillez patienter…','Espera…','Attendi…','Παρακαλώ περιμένετε…','请稍候…','処理中…','처리 중…'],
  emailAuthError: ['İşlem tamamlanamadı. Bilgileri kontrol edip tekrar deneyin.','Could not complete the request. Check your details and try again.','Vorgang fehlgeschlagen. Prüfen Sie Ihre Angaben.','Impossible de terminer. Vérifiez vos informations.','No se pudo completar. Revisa tus datos.','Operazione non riuscita. Controlla i dati.','Η ενέργεια απέτυχε. Ελέγξτε τα στοιχεία σας.','操作未完成，请检查信息后重试。','完了できませんでした。入力内容をご確認ください。','처리하지 못했습니다. 정보를 확인하세요.'],
  emailInUse: ['Bu e-posta zaten kayıtlı. Giriş yapmayı deneyin.','This email is already registered. Try signing in.','Diese E-Mail ist bereits registriert. Melden Sie sich an.','Cet e-mail est déjà inscrit. Essayez de vous connecter.','Este correo ya está registrado. Intenta iniciar sesión.','Questa e-mail è già registrata. Prova ad accedere.','Αυτό το email είναι ήδη καταχωρισμένο. Δοκιμάστε να συνδεθείτε.','该邮箱已注册，请尝试登录。','このメールは登録済みです。ログインしてください。','이미 등록된 이메일입니다. 로그인하세요.'],
  emailInvalidCredentials: ['E-posta veya şifre hatalı.','Incorrect email or password.','E-Mail oder Passwort ist falsch.','E-mail ou mot de passe incorrect.','Correo o contraseña incorrectos.','E-mail o password non corretti.','Λάθος email ή κωδικός.','邮箱或密码不正确。','メールまたはパスワードが違います。','이메일 또는 비밀번호가 올바르지 않습니다.'],
  googleConnected: ['Google ile bağlı','Connected with Google','Mit Google verbunden','Connecté avec Google','Conectado con Google','Collegato con Google','Συνδεδεμένο με Google','已连接 Google','Googleと連携済み','Google 연결됨'],
  appleConnected: ['Apple ile bağlı','Connected with Apple','Mit Apple verbunden','Connecté avec Apple','Conectado con Apple','Collegato con Apple','Συνδεδεμένο με Apple','已连接 Apple','Appleと連携済み','Apple 연결됨'],
  logout: ['Çıkış','Sign out','Abmelden','Déconnexion','Cerrar sesión','Esci','Αποσύνδεση','退出登录','ログアウト','로그아웃'],
  deleteButton: ['Hesabı sil','Delete account','Konto löschen','Supprimer le compte','Eliminar cuenta','Elimina account','Διαγραφή λογαριασμού','删除账户','アカウントを削除','계정 삭제'],
  deleting: ['Siliniyor…','Deleting…','Wird gelöscht…','Suppression…','Eliminando…','Eliminazione…','Διαγραφή…','正在删除…','削除中…','삭제 중…'],
  deleteConfirmTitle: ['Hesabı kalıcı olarak sil?','Permanently delete account?','Konto endgültig löschen?','Supprimer définitivement le compte ?','¿Eliminar la cuenta definitivamente?','Eliminare definitivamente l’account?','Οριστική διαγραφή λογαριασμού;','永久删除账户？','アカウントを完全に削除しますか？','계정을 영구 삭제할까요?'],
  deleteConfirmBody: ['Profilin, Şans Kurabiyesi geçmişin ve kullanım kayıtların silinecek. Bu işlem geri alınamaz.','Your profile, Fortune Cookie history and usage records will be deleted. This cannot be undone.','Profil, Glückskeks-Verlauf und Nutzungsdaten werden gelöscht. Dies kann nicht rückgängig gemacht werden.','Votre profil, votre historique et vos données d’utilisation seront supprimés. Cette action est irréversible.','Se eliminarán tu perfil, historial y registros de uso. Esta acción no se puede deshacer.','Profilo, cronologia e dati di utilizzo saranno eliminati. L’azione è irreversibile.','Το προφίλ, το ιστορικό και οι εγγραφές χρήσης θα διαγραφούν. Η ενέργεια δεν αναιρείται.','你的个人资料、幸运饼干历史和使用记录将被删除。此操作无法撤销。','プロフィール、履歴、利用記録が削除されます。この操作は取り消せません。','프로필, 포춘 쿠키 기록 및 사용 기록이 삭제되며 되돌릴 수 없습니다.'],
  cancel: ['Vazgeç','Cancel','Abbrechen','Annuler','Cancelar','Annulla','Ακύρωση','取消','キャンセル','취소'],
  confirmDelete: ['Evet, hesabımı sil','Yes, delete my account','Ja, Konto löschen','Oui, supprimer mon compte','Sí, eliminar mi cuenta','Sì, elimina il mio account','Ναι, διαγραφή λογαριασμού','是，删除我的账户','はい、削除します','예, 계정 삭제'],
  deleteSuccess: ['Hesabın ve kayıtlı verilerin kalıcı olarak silindi.','Your account and saved data were permanently deleted.','Konto und gespeicherte Daten wurden dauerhaft gelöscht.','Votre compte et vos données ont été définitivement supprimés.','Tu cuenta y los datos guardados se eliminaron definitivamente.','Account e dati salvati sono stati eliminati definitivamente.','Ο λογαριασμός και τα δεδομένα διαγράφηκαν οριστικά.','账户和保存的数据已永久删除。','アカウントと保存データを完全に削除しました。','계정과 저장된 데이터가 영구 삭제되었습니다.'],
  deleteError: ['Hesap silinemedi. Yeniden giriş yapıp tekrar deneyin.','Account could not be deleted. Sign in again and retry.','Konto konnte nicht gelöscht werden. Bitte erneut anmelden.','Impossible de supprimer le compte. Reconnectez-vous et réessayez.','No se pudo eliminar la cuenta. Vuelve a iniciar sesión.','Impossibile eliminare l’account. Accedi di nuovo e riprova.','Η διαγραφή απέτυχε. Συνδεθείτε ξανά και δοκιμάστε.','无法删除账户。请重新登录后重试。','削除できませんでした。再ログインしてお試しください。','계정을 삭제하지 못했습니다. 다시 로그인해 주세요.'],
  loadingOpened: ['Kurabiyen açıldı','Your cookie opened','Dein Keks ist geöffnet','Votre biscuit est ouvert','Tu galleta se abrió','Il biscotto si è aperto','Το μπισκότο άνοιξε','幸运饼干已打开','クッキーが開きました','쿠키가 열렸습니다'],
  loadingReading: ['Yıldız haritan yorumlanıyor','Reading your star chart','Dein Sternbild wird gelesen','Lecture de votre carte astrale','Interpretando tu carta astral','Lettura del tuo tema astrale','Ανάγνωση του αστρικού χάρτη','正在解读你的星盘','星図を読み解いています','별자리를 해석 중입니다'],
  loadingSelecting: ['Sana özel mesaj seçiliyor','Choosing your personal message','Deine persönliche Botschaft wird gewählt','Choix de votre message personnel','Eligiendo tu mensaje personal','Scelta del tuo messaggio personale','Επιλογή προσωπικού μηνύματος','正在挑选专属寄语','あなたへの言葉を選んでいます','맞춤 메시지를 고르는 중입니다'],
  loadingFinishing: ['Son dokunuşlar yapılıyor','Adding the final touches','Letzte Feinheiten','Dernières touches','Dando los últimos retoques','Ultimi ritocchi','Τελευταίες πινελιές','正在进行最后调整','仕上げをしています','마무리 중입니다']
  ,welcome: ['Hoş geldin, {name}!','Welcome, {name}!','Willkommen, {name}!','Bienvenue, {name} !','¡Bienvenido, {name}!','Benvenuto, {name}!','Καλώς ήρθες, {name}!','欢迎，{name}！','ようこそ、{name}さん！','환영합니다, {name}님!'],
  userFallback: ['Kullanıcı','User','Nutzer','Utilisateur','Usuario','Utente','Χρήστης','用户','ユーザー','사용자'],
  signingGoogle: ['Google ile giriş yapılıyor…','Signing in with Google…','Anmeldung mit Google…','Connexion avec Google…','Iniciando sesión con Google…','Accesso con Google…','Σύνδεση με Google…','正在使用 Google 登录…','Googleでログイン中…','Google 로그인 중…'],
  signingApple: ['Apple ile giriş yapılıyor…','Signing in with Apple…','Anmeldung mit Apple…','Connexion avec Apple…','Iniciando sesión con Apple…','Accesso con Apple…','Σύνδεση με Apple…','正在使用 Apple 登录…','Appleでログイン中…','Apple 로그인 중…'],
  signInFailed: ['Giriş yapılamadı: {error}','Sign-in failed: {error}','Anmeldung fehlgeschlagen: {error}','Échec de la connexion : {error}','Error de inicio de sesión: {error}','Accesso non riuscito: {error}','Η σύνδεση απέτυχε: {error}','登录失败：{error}','ログインできませんでした：{error}','로그인 실패: {error}'],
  cancelled: ['İşlem iptal edildi','Operation cancelled','Vorgang abgebrochen','Opération annulée','Operación cancelada','Operazione annullata','Η ενέργεια ακυρώθηκε','操作已取消','操作がキャンセルされました','작업이 취소되었습니다']
  ,personalAiOpen: ['Kişisel AI Şans Kurabiyesi açık','Personal AI Fortune Cookie active','Persönlicher AI-Glückskeks aktiv','Fortune Cookie IA personnel actif','Galleta IA personal activa','Biscotto AI personale attivo','Προσωπικό AI μπισκότο ενεργό','个性化 AI 幸运饼干已启用','パーソナルAIフォーチュンクッキー有効','맞춤 AI 포춘 쿠키 활성'],
  rewardedAiOpen: ['Ödüllü AI Şans Kurabiyesi açık','Rewarded AI Fortune Cookie active','Belohnungs-AI-Glückskeks aktiv','Fortune Cookie IA récompensé actif','Galleta IA con recompensa activa','Biscotto AI premio attivo','AI μπισκότο ανταμοιβής ενεργό','奖励 AI 幸运饼干已启用','リワードAIフォーチュンクッキー有効','보상형 AI 포춘 쿠키 활성']
  ,aiUnavailable: ['Şans Kurabiyesi hazırlanamadı. Lütfen tekrar deneyin.','The Fortune Cookie could not be prepared. Please try again.','Der Glückskeks konnte nicht vorbereitet werden. Bitte erneut versuchen.','Le Fortune Cookie n’a pas pu être préparé. Réessayez.','No se pudo preparar la galleta. Inténtalo de nuevo.','Impossibile preparare il biscotto. Riprova.','Το μπισκότο τύχης δεν ετοιμάστηκε. Δοκιμάστε ξανά.','无法准备幸运饼干，请重试。','フォーチュンクッキーを準備できませんでした。もう一度お試しください。','포춘 쿠키를 준비하지 못했습니다. 다시 시도해 주세요.']
};

export const appMessages = Object.fromEntries(
  SUPPORTED_LANGUAGES.map((lang, index) => [
    lang,
    Object.fromEntries(Object.entries(rows).map(([key, values]) => [key, values[index]]))
  ])
);

export function normalizeLanguage(value, fallback = 'en') {
  const raw = String(value || '').trim().toLowerCase().replace('_', '-');
  const base = raw.split('-')[0];
  return SUPPORTED_LANGUAGES.includes(base) ? base : fallback;
}

export function translate(lang, key, vars = {}) {
  const normalized = normalizeLanguage(lang);
  let value = appMessages[normalized]?.[key] || appMessages.en[key] || key;
  for (const [name, replacement] of Object.entries(vars)) {
    value = value.replaceAll(`{${name}}`, String(replacement));
  }
  return value;
}
